notifications:
  email: false

# code language
language: python
python:
  - "3.6"

before_install:
  - sudo apt-get --only-upgrade install -y sqlite3
  - sudu apt-get update

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage codecov

# command to run tests
script:
  - coverage run --source='.' manage.py test

# command to run after success
after_success:
  - codecov
