# Generated by Django 2.1.2 on 2018-11-05 17:45

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concurrency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('concurrentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concurrency.ConcurrentModel')),
                ('title', models.CharField(max_length=100)),
                ('ingress', models.TextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('datetime_published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-datetime_published',),
            },
            bases=('concurrency.concurrentmodel',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.Article')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('location_external', models.BooleanField(default=False)),
                ('signup_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-start_date', '-start_time'),
            },
            bases=('news.article',),
        ),
    ]
