# Generated by Django 2.1.5 on 2020-01-23 10:24

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concurrency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('concurrentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concurrency.ConcurrentModel')),
                ('title', models.CharField(max_length=100)),
                ('ingress', models.TextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, default=None, null=True, upload_to='web/img/article/banners')),
                ('published', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
            bases=('concurrency.concurrentmodel',),
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='article/files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.Article')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_date', models.DateField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('location_url', models.URLField(blank=True, max_length=250, null=True)),
                ('location_url_embed', models.URLField(blank=True, max_length=250, null=True)),
                ('location_off_campus', models.BooleanField(default=False)),
                ('signup_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-start_date', '-start_time'),
            },
            bases=('news.article',),
        ),
        migrations.AddField(
            model_name='articlefile',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='news.Article'),
        ),
    ]
