# Generated by Django 2.1.5 on 2019-01-19 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 16, 20, 29, 353558, tzinfo=utc)),
        ),
    ]
