# Generated by Django 2.1.5 on 2020-01-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefile',
            name='file',
            field=models.FileField(null=True, upload_to='article/files/'),
        ),
    ]
