# Generated by Django 2.1.5 on 2019-01-22 23:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190119_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 23, 37, 29, 548556, tzinfo=utc)),
        ),
    ]
