# Generated by Django 2.1.5 on 2020-02-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200123_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiletoArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='article/files/')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='news.Article')),
            ],
        ),
        migrations.RemoveField(
            model_name='articlefile',
            name='article',
        ),
        migrations.DeleteModel(
            name='ArticleFile',
        ),
    ]
