# Generated by Django 2.1.5 on 2019-01-20 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190119_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 14, 6, 9, 422826, tzinfo=utc)),
        ),
    ]
