# Generated by Django 2.2.6 on 2020-08-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200227_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiletoArticle',
            new_name='ArticleFile',
        ),
    ]
