# Generated by Django 2.1.5 on 2019-01-20 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190120_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 14, 14, 35, 811515, tzinfo=utc)),
        ),
    ]
