# Generated by Django 2.0.5 on 2018-05-07 19:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_ingress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.Article')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('hoopla_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('start_date', 'start_time'),
            },
            bases=('news.article',),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
