# Generated by Django 2.1.5 on 2019-01-31 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190124_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 19, 16, 59, 257749, tzinfo=utc)),
        ),
    ]
