# Generated by Django 2.1.5 on 2019-03-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190221_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
    ]
