# Generated by Django 2.1.5 on 2019-01-20 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190120_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 14, 21, 52, 601336, tzinfo=utc)),
        ),
    ]
