# Generated by Django 2.1.5 on 2019-01-20 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190120_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 14, 24, 59, 889763, tzinfo=utc)),
        ),
    ]
