# Generated by Django 2.0.13 on 2019-04-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_pinned'),
        ('news', '0005_auto_20190314_2011'),
    ]

    operations = [
    ]
