# Generated by Django 2.0.5 on 2018-05-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_date', '-start_time')},
        ),
    ]
