# Generated by Django 2.0.5 on 2018-08-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180509_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='signup_url',
        ),
    ]
