# Generated by Django 2.1.5 on 2019-01-20 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='creator',
            new_name='content_creator',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='author',
        ),
        migrations.AddField(
            model_name='resource',
            name='added_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
