# Generated by Django 2.0.5 on 2019-01-04 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='starred_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='starred_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
