# Generated by Django 2.0.5 on 2018-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20180816_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resource.Tag'),
        ),
    ]
