# Generated by Django 2.2.6 on 2020-08-08 13:00

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vervgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500)),
                ('form_link', models.CharField(blank=True, max_length=750, null=True)),
                ('application_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-application_end_date',),
            },
        ),
        migrations.CreateModel(
            name='Verv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000)),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='web/img/verv/')),
                ('Vervgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verv', to='verv.Vervgroup')),
                ('members', models.ManyToManyField(blank=True, related_name='verv_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
