# Generated by Django 3.1.2 on 2021-03-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verv',
            old_name='Vervgroup',
            new_name='VervGroup',
        ),
    ]
