# Generated by Django 2.0.5 on 2018-05-09 18:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbox',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
