# Generated by Django 2.1.5 on 2019-01-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlepage',
            name='id',
        ),
        migrations.AlterField(
            model_name='singlepage',
            name='url',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
