# Generated by Django 2.1.5 on 2019-01-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0002_auto_20190114_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlepage',
            old_name='url',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='feedfile',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='single_page.SinglePage', to_field='url'),
        ),
    ]
