# Generated by Django 2.1.5 on 2019-01-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0003_auto_20190114_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedfile',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='single_page.SinglePage'),
        ),
    ]
