# Generated by Django 2.1.5 on 2019-01-13 18:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500),
        ),
    ]
