# Generated by Django 2.0.5 on 2018-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='application_end',
        ),
        migrations.AddField(
            model_name='applicantpool',
            name='application_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
