# Generated by Django 2.1.5 on 2019-01-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('-application_end_date',)},
        ),
    ]
