# Generated by Django 2.0.5 on 2019-01-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
