# Generated by Django 2.0.5 on 2018-11-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181112_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantpool',
            old_name='users',
            new_name='applicants',
        ),
    ]
