# Generated by Django 2.0.5 on 2019-01-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_collection_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
