# Generated by Django 2.0.5 on 2018-09-28 16:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='web/img/profiles/')),
                ('committee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.Committee')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000)),
                ('application_end', models.DateField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('form_link', models.CharField(blank=True, max_length=750, null=True)),
                ('applicants', models.ManyToManyField(blank=True, related_name='project_applications', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
                ('rejected_applicants', models.ManyToManyField(blank=True, related_name='project_rejections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('members', models.ManyToManyField(blank=True, related_name='skill', to='user_profile.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to='user_profile.Skill'),
        ),
    ]
