# Generated by Django 2.0.5 on 2018-10-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='applicants',
        ),
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rejected_applicants',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
