# Generated by Django 2.0.5 on 2018-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180711_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='project', to='user_profile.Profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='skill', to='user_profile.Profile'),
        ),
    ]
