# Generated by Django 2.0.5 on 2018-07-12 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_auto_20180712_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='applicants',
        ),
        migrations.AddField(
            model_name='project',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='project_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='rejected_applicants',
        ),
        migrations.AddField(
            model_name='project',
            name='rejected_applicants',
            field=models.ManyToManyField(blank=True, related_name='project_application_rejected', to=settings.AUTH_USER_MODEL),
        ),
    ]
