# Generated by Django 2.0.5 on 2018-07-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180711_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=140, null=True, unique=True),
        ),
    ]
