# Generated by Django 2.0.5 on 2018-07-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_committee'),
        ('user_profile', '0005_auto_20180711_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.Committee'),
        ),
    ]
