# Generated by Django 2.0.5 on 2018-07-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='web/img/profiles/'),
        ),
    ]
