# Generated by Django 2.0.5 on 2018-07-16 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20180714_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='project_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='rejected_applicants',
            field=models.ManyToManyField(blank=True, related_name='project_rejections', to=settings.AUTH_USER_MODEL),
        ),
    ]
