# Generated by Django 2.0.5 on 2018-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_remove_profile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='form_link',
            field=models.CharField(blank=True, max_length=750, null=True, unique=True),
        ),
    ]
