# Generated by Django 2.0.5 on 2018-09-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_project_form_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='form_link',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
    ]
