# Generated by Django 3.1.2 on 2021-03-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('content', models.TextField(max_length=280)),
                ('likes', models.IntegerField(default=0)),
                ('tweet_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-likes'],
            },
        ),
    ]
