# Generated by Django 3.1.2 on 2021-02-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['likes'],
            },
        ),
    ]
