# Generated by Django 2.2.4 on 2020-01-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptake',
            name='is_uptake',
            field=models.BooleanField(default=True),
        ),
    ]
