# Generated by Django 2.2.4 on 2020-01-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptake', '0002_uptake_is_uptake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uptake',
            options={},
        ),
        migrations.RenameField(
            model_name='uptake',
            old_name='is_uptake',
            new_name='active_uptake',
        ),
        migrations.RemoveField(
            model_name='uptake',
            name='published',
        ),
        migrations.AddField(
            model_name='uptake',
            name='title',
            field=models.CharField(default='Cogito har opptak!', max_length=255),
        ),
    ]
