# Generated by Django 2.2.4 on 2020-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptake', '0003_auto_20200115_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptake',
            name='button_link',
            field=models.URLField(),
        ),
    ]
